### PR TITLE
update Model with BillingAddress for Payins and PayinsMulit

### PR DESCRIPTION
**Pull request by Faulk13**

### CODE REVIEW

**Comment by Hraph** [comment]
Hi Rémi, thanks for this PR. Have Paygreen updated their swagger API definition?

**Comment by Faulk13** [comment]
Hi Hraph, we use your bundle for a project and we need to pass the billingAddress to paygreen like in documentation here => https://paygreen.fr/documentation/api-documentation-categorie?cat=all#tag/Les-transactions%2Fpaths%2F~1api~1%7Bidentifiant%7D~1payins~1transaction~1cash%2Fpost.

That's why I did this pull request. I hope it's enough.. :) 

I will send you another PR for Sylius Paygreen Plugin ;)

**Comment by Faulk13** [comment]
Do you think this PR will accept soon ? If not, I will must try another solution :)

**Comment by Hraph** [comment]
Hello Rémi,

Sorry for this long response, I had to find some time to update this lib.
I've updated the lib with the latest specs from paygreen. Shipping and billing addresses fields are not available.

Thanks for your time and your commitment.

**Pull request closed without merging**
